# 开发环境配置
app:
  prefix: ''
  port: 8181
  logger:
    # 项目日志存储路径，相对路径（相对本项目根目录）或绝对路径
    dir: '../logs'
  # 文件相关
  file:
    # 是否为本地文件服务或cos
    isLocal: true
    # location 文件上传后存储目录，相对路径（相对本项目根目录）或绝对路径
    location: '../upload'
    # 文件服务器地址，这是开发环境的配置 生产环境请自行配置成可访问域名
    domain: 'http://localhost:8181'
    # 文件虚拟路径, 必须以 / 开头， 如 http://localhost:8081/static/****.jpg  , 如果不需要则 设置 ''
    serveRoot: '/upload'
    # 文件大小限制，单位M
    maxSize: 10
# 腾讯云cos配置
cos:
  secretId: ''
  secretKey: ''
  bucket: ''
  region: ''
  domain: ''
  location: ''
# 数据库配置
db:
  postgres:
    host: '192.168.0.30'
    username: 'nest'
    password: 'nest'
    database: 'nest'
    port: 5432
    ssldisable: false
    # charset: 'utf8mb4'
    logger: 'file'
    logging: true
    multipleStatements: true
    dropSchema: false
    synchronize: false
    supportBigNumbers: true
    bigNumberStrings: true
    
  odoo18:
    host: '192.168.0.40'
    database: 'Odoo18'
    username: 'odoo'
    password: 'odoo'
    port: 5432
    ssldisable: false
    # charset: 'utf8mb4'
    logger: 'file'
    logging: true
    multipleStatements: true
    dropSchema: false
    synchronize: false
    supportBigNumbers: true
    bigNumberStrings: true

# 公共websocket配置 path为odoo websocket服务运行端口
websocket:
  domain: 'https://odoows.tbird.com'
  path: 'http://192.168.0.40:8072'

# redis 配置
redis:
  host: '192.168.0.112'
  password: ''
  port: 6379
  db: 2
  keyPrefix: ''

# jwt 配置
jwt:
  secretkey: 'you_secretkey'
  expiresin: '1h'
  refreshExpiresIn: '2h'
# 权限 白名单配置 注意post等方法与路由一致
perm:
  router:
    whitelist:
      [
        { path: '/moreinfo', method: 'GET'},
        { path: '/auth/totp/verify', method: 'POST'},
        { path: '/auth/totp/qrcode', method: 'POST'},
        { path: '/auth/totp/disable/:userId', method: 'DELETE', skipToken: false },
        { path: '/register', method: 'POST' },
        { path: '/smscode', method: 'POST' },
        { path: '/login', method: 'POST' },
        { path: '/logout', method: 'POST' },
        { path: '/perm/{id}', method: 'GET' },
        { path: '/upload', method: 'POST' },
        # { path: '/emrManage/dynamicOptions/deptOptionlist', method: 'GET'},
        { path: '/emrManage/dynamicOptions/getTemplateFeildList', method: 'GET'}
      ]

# 用户相关
# 初始密码， 重置密码
user:
  initialPassword: '123456'
  # smsserver: 'http://192.168.0.108:8080/sendMessage'  在数据库中sys_config中定义
