/** 定义业务类型枚举 */
export const BusinessEnum = {
  OUTPATIENT: '门诊',
  INPATIENT: '住院',
  CT: 'CT',
  PHYSICAL_EXAMINATION: '体检',
  EXAMINATION: '检查',
  TESTING: '检验'
}

/** 定义payload格式类型枚举 */
export const PayloadTypeEnum = {
  FORM: '表单',
  MARKDOWN: 'markdown',
}


/** 定义单条记录（payload）Form卡片 */
export const MRCard = {
  "key": 52497,
  "type": "card",
  "category": "container",
  "icon": "card",
  "widgetList": [],
  "options": {
    "name": "newRecord",
    "label": "newRecord",
    "hidden": false,
    "folded": false,
    "showFold": true,
    "cardWidth": "100%",
    "shadow": "never",
    "customClass": []
  },
  "id": "card47702"
}

/** vform表单基础配置json */
export const vFormConfigJson = {
  "widgetList": [],
  "formConfig": {
    "modelName": "formData",
    "refName": "vForm",
    "rulesName": "rules",
    "labelWidth": 150,
    "labelPosition": "left",
    "size": "",
    "labelAlign": "label-left-align",
    "cssCode": "",
    "customClass": [],
    "functions": "",
    "layoutType": "PC",
    "jsonVersion": 3,
    "onFormCreated": "",
    "onFormMounted": "",
    "onFormDataChange": ""
  }
}
/** 定义vform编辑器组件配置 */
export const vFormWidgets = {
  inputWidget: {
    "key": 20098,
    "type": "input",
    "icon": "text-field",
    "formItemFlag": true,
    "options": {
      "name": "本地设备",
      "label": "本地设备",
      "labelAlign": "",
      "type": "text",
      "defaultValue": "",
      "placeholder": "",
      "columnWidth": "200px",
      "size": "",
      "labelWidth": null,
      "labelHidden": false,
      "readonly": false,
      "disabled": false,
      "hidden": false,
      "clearable": true,
      "showPassword": false,
      "required": false,
      "requiredHint": "",
      "validation": "",
      "validationHint": "",
      "customClass": "",
      "labelIconClass": null,
      "labelIconPosition": "rear",
      "labelTooltip": null,
      "minLength": null,
      "maxLength": null,
      "showWordLimit": false,
      "prefixIcon": "",
      "suffixIcon": "",
      "appendButton": false,
      "appendButtonDisabled": false,
      "buttonIcon": "custom-search",
      "onCreated": "",
      "onMounted": "",
      "onInput": "",
      "onChange": "",
      "onFocus": "",
      "onBlur": "",
      "onValidate": "",
      "onAppendButtonClick": ""
    },
    "id": "本地设备"
  },
  numberWidget: {
    "key": 18758,
    "type": "number",
    "icon": "number-field",
    "formItemFlag": true,
    "options": {
      "name": "月收入",
      "label": "月收入",
      "labelAlign": "",
      "defaultValue": 0,
      "placeholder": "",
      "columnWidth": "200px",
      "size": "",
      "labelWidth": null,
      "labelHidden": false,
      "disabled": false,
      "hidden": false,
      "required": false,
      "requiredHint": "",
      "validation": "",
      "validationHint": "",
      "customClass": "",
      "labelIconClass": null,
      "labelIconPosition": "rear",
      "labelTooltip": null,
      "min": -100000000000,
      "max": 100000000000,
      "precision": 0,
      "step": 1,
      "controlsPosition": "right",
      "onCreated": "",
      "onMounted": "",
      "onChange": "",
      "onFocus": "",
      "onBlur": "",
      "onValidate": ""
    },
    "id": "月收入"
  },
  radioWidget: {
    "key": 78383,
    "type": "radio",
    "icon": "radio-field",
    "formItemFlag": true,
    "options": {
      "name": "radio106897",
      "label": "radio",
      "labelAlign": "",
      "defaultValue": null,
      "columnWidth": "200px",
      "size": "",
      "displayStyle": "inline",
      "buttonStyle": false,
      "border": false,
      "labelWidth": null,
      "labelHidden": false,
      "disabled": false,
      "hidden": false,
      "optionItems": [
        {
          "label": "radio 1",
          "value": 1
        },
        {
          "label": "radio 2",
          "value": 2
        },
        {
          "label": "radio 3",
          "value": 3
        }
      ],
      "required": false,
      "requiredHint": "",
      "validation": "",
      "validationHint": "",
      "customClass": "",
      "labelIconClass": null,
      "labelIconPosition": "rear",
      "labelTooltip": null,
      "onCreated": "",
      "onMounted": "",
      "onChange": "",
      "onValidate": ""
    },
    "id": "月收入"
  },
  textareaWidget: {
    "key": 83155,
    "type": "textarea",
    "icon": "textarea-field",
    "formItemFlag": true,
    "options": {
      "name": "textarea99752",
      "label": "textarea",
      "labelAlign": "",
      "rows": 3,
      "defaultValue": "",
      "placeholder": "",
      "columnWidth": "200px",
      "size": "",
      "labelWidth": null,
      "labelHidden": false,
      "readonly": false,
      "disabled": false,
      "hidden": false,
      "required": false,
      "requiredHint": "",
      "validation": "",
      "validationHint": "",
      "customClass": "",
      "labelIconClass": null,
      "labelIconPosition": "rear",
      "labelTooltip": null,
      "minLength": null,
      "maxLength": null,
      "showWordLimit": false,
      "onCreated": "",
      "onMounted": "",
      "onInput": "",
      "onChange": "",
      "onFocus": "",
      "onBlur": "",
      "onValidate": ""
    },
    "id": "textarea99752"
  },
  checkboxWidget: {
    "key": 79952,
    "type": "checkbox",
    "icon": "checkbox-field",
    "formItemFlag": true,
    "options": {
      "name": "checkbox77405",
      "label": "checkbox",
      "labelAlign": "",
      "defaultValue": [],
      "columnWidth": "200px",
      "size": "",
      "displayStyle": "inline",
      "buttonStyle": false,
      "border": false,
      "labelWidth": null,
      "labelHidden": false,
      "disabled": false,
      "hidden": false,
      "optionItems": [
        {
          "label": "check 1",
          "value": 1
        },
        {
          "label": "check 2",
          "value": 2
        },
        {
          "label": "check 3",
          "value": 3
        }
      ],
      "required": false,
      "requiredHint": "",
      "validation": "",
      "validationHint": "",
      "customClass": [],
      "labelIconClass": null,
      "labelIconPosition": "rear",
      "labelTooltip": null,
      "onCreated": "",
      "onMounted": "",
      "onChange": "",
      "onValidate": ""
    },
    "id": "checkbox77405"
  },
  selectWidget: {
    "key": 34896,
    "type": "select",
    "icon": "select-field",
    "formItemFlag": true,
    "options": {
      "name": "select104483",
      "label": "select",
      "labelAlign": "",
      "defaultValue": "",
      "placeholder": "",
      "columnWidth": "200px",
      "size": "",
      "labelWidth": null,
      "labelHidden": false,
      "disabled": false,
      "hidden": false,
      "clearable": true,
      "filterable": false,
      "allowCreate": false,
      "remote": false,
      "automaticDropdown": false,
      "multiple": false,
      "multipleLimit": 0,
      "optionItems": [
        {
          "label": "select 1",
          "value": 1
        },
        {
          "label": "select 2",
          "value": 2
        },
        {
          "label": "select 3",
          "value": 3
        }
      ],
      "required": false,
      "requiredHint": "",
      "validation": "",
      "validationHint": "",
      "customClass": "",
      "labelIconClass": null,
      "labelIconPosition": "rear",
      "labelTooltip": null,
      "onCreated": "",
      "onMounted": "",
      "onRemoteQuery": "",
      "onChange": "",
      "onFocus": "",
      "onBlur": "",
      "onValidate": ""
    },
    "id": "select104483"
  },
  timeWidget: {
    "key": 96927,
    "type": "time",
    "icon": "time-field",
    "formItemFlag": true,
    "options": {
      "name": "time72229",
      "label": "time",
      "labelAlign": "",
      "defaultValue": null,
      "placeholder": "",
      "columnWidth": "200px",
      "size": "",
      "autoFullWidth": true,
      "labelWidth": null,
      "labelHidden": false,
      "readonly": false,
      "disabled": false,
      "hidden": false,
      "clearable": true,
      "editable": false,
      "format": "HH:mm:ss",
      "required": false,
      "requiredHint": "",
      "validation": "",
      "validationHint": "",
      "customClass": "",
      "labelIconClass": null,
      "labelIconPosition": "rear",
      "labelTooltip": null,
      "onCreated": "",
      "onMounted": "",
      "onChange": "",
      "onFocus": "",
      "onBlur": "",
      "onValidate": ""
    },
    "id": "time72229"
  },
  timeRangeWidget: {
    "key": 42220,
    "type": "time-range",
    "icon": "time-range-field",
    "formItemFlag": true,
    "options": {
      "name": "timerange45477",
      "label": "time-range",
      "labelAlign": "",
      "defaultValue": null,
      "startPlaceholder": "",
      "endPlaceholder": "",
      "columnWidth": "200px",
      "size": "",
      "autoFullWidth": true,
      "labelWidth": null,
      "labelHidden": false,
      "readonly": false,
      "disabled": false,
      "hidden": false,
      "clearable": true,
      "editable": false,
      "format": "HH:mm:ss",
      "required": false,
      "requiredHint": "",
      "validation": "",
      "validationHint": "",
      "customClass": "",
      "labelIconClass": null,
      "labelIconPosition": "rear",
      "labelTooltip": null,
      "onCreated": "",
      "onMounted": "",
      "onChange": "",
      "onFocus": "",
      "onBlur": "",
      "onValidate": ""
    },
    "id": "timerange45477"
  },
  dateWidget: {
    "key": 108662,
    "type": "date",
    "icon": "date-field",
    "formItemFlag": true,
    "options": {
      "name": "date94302",
      "label": "date",
      "labelAlign": "",
      "type": "date",
      "defaultValue": null,
      "placeholder": "",
      "columnWidth": "200px",
      "size": "",
      "autoFullWidth": true,
      "labelWidth": null,
      "labelHidden": false,
      "readonly": false,
      "disabled": false,
      "hidden": false,
      "clearable": true,
      "editable": false,
      "format": "YYYY-MM-DD",
      "valueFormat": "YYYY-MM-DD",
      "required": false,
      "requiredHint": "",
      "validation": "",
      "validationHint": "",
      "customClass": "",
      "labelIconClass": null,
      "labelIconPosition": "rear",
      "labelTooltip": null,
      "onCreated": "",
      "onMounted": "",
      "onChange": "",
      "onFocus": "",
      "onBlur": "",
      "onValidate": ""
    },
    "id": "date94302"
  },
  dateRangeWidget: {
    "key": 6908,
    "type": "date-range",
    "icon": "date-range-field",
    "formItemFlag": true,
    "options": {
      "name": "daterange80438",
      "label": "date-range",
      "labelAlign": "",
      "type": "daterange",
      "defaultValue": null,
      "startPlaceholder": "",
      "endPlaceholder": "",
      "columnWidth": "200px",
      "size": "",
      "autoFullWidth": true,
      "labelWidth": null,
      "labelHidden": false,
      "readonly": false,
      "disabled": false,
      "hidden": false,
      "clearable": true,
      "editable": false,
      "format": "YYYY-MM-DD",
      "valueFormat": "YYYY-MM-DD",
      "required": false,
      "requiredHint": "",
      "validation": "",
      "validationHint": "",
      "customClass": "",
      "labelIconClass": null,
      "labelIconPosition": "rear",
      "labelTooltip": null,
      "onCreated": "",
      "onMounted": "",
      "onChange": "",
      "onFocus": "",
      "onBlur": "",
      "onValidate": ""
    },
    "id": "daterange80438"
  }
}